repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(scripts/|archive/)
      - id: ruff-format
        exclude: ^(scripts/|archive/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: end-of-file-fixer
        exclude: ^(archive/|data/legacy/|\.idea/)
      - id: trailing-whitespace
        exclude: ^(archive/|data/legacy/|\.idea/)
      - id: check-merge-conflict
      - id: debug-statements
        exclude: ^(scripts/legacy/|archive/)
